name: Build and Publish Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .
          pip install .[dev,test]

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Run tests
        run: |
          python example/flaskr_tests.py

      - name: Build docs
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: docs
          path: "docs"

      - name: Upload test documentation
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        run: |
          rm -rf ../docs/main/*
          cp -r docs/build/html/* ../docs/main/
          cd ../docs
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git add . -A
          git commit -m "Update docs for $GITHUB_SHA" || echo "No changes to commit"
          git push
          cd $GITHUB_WORKSPACE

      - name: Publish package to Test PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: true

      - name: Upload documentation
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          rm -rf ../docs/latest/*
          cp -r docs/build/html/* ../docs/latest/
          cp -r docs/build/html/* ../docs/$TAG_NAME/
          cd ../docs
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          sed -i 's|        <!-- bot maker-->|        <!-- bot maker-->\n        <li><a href="https://croydon.github.io/flask-xml-rpc-reloaded/$TAG_NAME/" title="Documentation for v$TAG_NAME">Version $TAG_NAME<a></li>|' index.html
          git add . -A
          git commit -m "Update docs for $GITHUB_SHA" || echo "No changes to commit"
          git push
          cd $GITHUB_WORKSPACE

      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
